export const MINI_PROJECTS_ARR = [
  "Simple-Form",
  "Controlled-Form",
  "React-Hook-Form",
  "Accordion",
  "Tic-Tac-Toe",
  "Search-Auto-Complete",
  "Tabs",
  "Model",
  "Image-Slider",
  "Github-User",
  "Star-Rating",
  "Type-Effect",
  "Tab-Transition",
  "Image-Scroll",
];
